Revert "update poetry.lock"
This reverts commit 93c83fb23e6af1b05c56603b48714e6e41a76363.

Revert this to fix failing github build error:

```
  scipy/cluster/_vq.c:196:12: fatal error: longintrepr.h: No such file or directory
```